### ISSUE TITLE
Can you provide your codes about cpp_wrappers based on tf2 and cuda11.0?

### ISSUE THREAD

**Issue by longmalongma** [hzykent/JSENet#4]
Can you provide your codes about cpp_wrappers based on tf2 and cuda11.0? I can compile it when I using tf2 and cuda11.0. Looking forward to your reply.

**Comment by hzykent** [comment]
Thank you for your interest. The cpp codes involved in this project are adopted from KPConv. I guess it would be a better idea to ask the author of KPConv directly.
