### ISSUE TITLE
Prepare data for S3DIS

### ISSUE THREAD

**Issue by mtli77** [hzykent/JSENet#5]
Hi @hzykent 

Thank you for your excellent work.
the closed issues https://github.com/hzykent/JSENet/issues/2 reported some mistakes in preparing the scannet.

I wonder in the S3DIS, does the 
https://github.com/hzykent/JSENet/blob/24f880d102e2f75fec23caf1ebf8f5d4a21b85d5/JSENet_code/dataset_modules/S3DIS.py#L247
Does the  `inds` should be replaced by `inds[0]` ?

Best regards!

**Comment by hzykent** [comment]
Thank you for your interest.

I think you are right. By the way, if you wanna do some experiments on S3DIS dataset, the processed data has been provided.

**Comment by mtli77** [comment]
> Thank you for your interest.
> 
> I think you are right. By the way, if you wanna do some experiments on S3DIS dataset, the processed data has been provided.

Yes, only the demo dataset of s3dis_area 5, while I want the whole dataset~
