### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by hilnkm** [hzykent/JSENet#7]
Can you publish the visualization code? Just getting started with 3d point cloud, don’t know how to draw it. Thank you very much!

**Comment by hzykent** [comment]
Thank you for your interest. For visualization, I simply wrote ply files with "x,y,z,r,g,b" and loaded them with meshlab and CloudCompare. The code for writing ply files is provided in "utils" folder. Meshlab and CloudCompare can be downloaded from their website for free.
